sidebar:
  default: cli
  showLabels: true
  searchBox: true
abilities:
  - id: dashboard
    order: 1
    enabled: true
  - id: apps
    order: 2
    enabled: true
    config:
      searchRoots:
        - { path: "/home/aaaa0ggmc/Apps", watch: true }
      confirmBeforeLaunch: true
  - id: mirror
    order: 3
    enabled: true
    config:
      mirrors:
        - { name: "USTC", url: "https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch" }
        - { name: "TUNA", url: "https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch" }
        - { name: "Aliyun", url: "https://mirrors.aliyun.com/archlinux/$repo/os/$arch" }
        - { name: "Official", url: "https://geo.mirror.pkgbuild.com/$repo/os/$arch" }
  - id: autostart
    order: 4
    enabled: true
  - id: systemd
    order: 5
    enabled: true
  - id: hardware
    order: 6
    enabled: true
  - id: display
    order: 7
    enabled: true
    config:
      wallpaperDir: "/home/aaaa0ggmc/Pictures/Wallpapers"
  - id: cli
    order: 8
    enabled: true
    config:
      historyLimit: 500
  - id: settings
    order: 9
    enabled: true
